services:
  copilot:
    build:
      context: .
      args:
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}
    image: d_copilot
    environment:
      COLORTERM: truecolor
      TZ: ${TZ:-Europe/Berlin}
    volumes:
      - ${HOST_WORKDIR}:${CONTAINER_WORKDIR}
    working_dir: ${CONTAINER_WORKDIR}
    stdin_open: true
    tty: true
